name: PHP Package
on:
  push:
  pull_request:
jobs:
  format-check:
    name: Check PSR12 Standarts
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
      - run: composer install
        shell: bash
      - run: composer format:check
        shell: bash
  tests:
    name: Run Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
      - run: composer install
        shell: bash
      - run: composer test
        shell: bash
